test: add test to catch concurrency issue with log audit
rond-authz/rond pull request #419
Opened 2024-12-23 19:33 UTC by davidebianchi

2024-12-23 20:10 UTC, davidebianchi commented
We could also enable the bench test to run with audit enabled, or to add a test case with the audit enabled. But the test on the sdk are useful (I also find the issue in the test logger in this way 😄)

2024-12-27 06:11 UTC, fredmaggiowski requested changes

2024-12-27 06:11 UTC, fredmaggiowski commented on internal/audit/agent.go
> +	SetGlobalLabels(Labels)
I'm not convinced about this method being part of the pool behaviour. 

The method is intended to set labels during policy evaluation on a specific agent, if such labels are shared between multiple agents we might still have concurrency issues. 

Moreover I don't see changes to the builtin rego func that is using the method which feels odd, I'm worried about some type assertion that is making the code compile but that won't work at runtime

2025-01-07 09:15 UTC, fredmaggiowski approved these changes
LGTM

2025-01-07 09:15 UTC, merged